from __future__ import annotations

import hashlib
import os

from datetime import datetime, timezone
from threading import Lock

from schemas.transaction import (
    ClassificationRequest,
    FailureCode,
    RecoveryStatus,
    GuardrailStatus,
    ExecutionStatus,
    AuditEvent,
    RecoveryExecutionResponse,
)

from services.failure_classifier import classify_failure
from services.recovery_engine import create_recovery_decision
from services.guardrail_engine import evaluate_guardrails

from services.persistence_service import (
    save_transaction,
    get_recovery_job_by_idempotency_key,
    reserve_recovery_job,
    complete_recovery_job,
    fail_recovery_job,
    append_audit_event as persist_audit_event,
    get_audit_events,
)


# =========================================================
# IN-MEMORY FALLBACK / TEST STORAGE
# =========================================================
#
# Supabase is now the persistent runtime store when:
#
#     RECOVERAI_PERSISTENCE_ENABLED=true
#
# These stores remain intentionally available for:
#
# - deterministic automated tests
# - Buildathon simulation fallback
# - temporary Supabase unavailability
#
# Before real external financial execution is enabled,
# persistence must become fail-closed rather than fallback.
# =========================================================

AUDIT_STORE: dict[str, list[AuditEvent]] = {}

IDEMPOTENCY_RESULT_STORE: dict[
    str,
    RecoveryExecutionResponse,
] = {}

IDEMPOTENCY_STATE: dict[str, str] = {}

STORE_LOCK = Lock()


# =========================================================
# SIMULATION CONFIGURATION
# =========================================================

RETRY_SUCCESS_PROBABILITY = {
    FailureCode.BANK_UNAVAILABLE: 0.72,
    FailureCode.NETWORK_ERROR: 0.82,
    FailureCode.PAYMENT_TIMEOUT: 0.68,
}


RETRY_ACTIONS = {
    "DELAYED_RETRY",
    "SHORT_RETRY",
    "VERIFY_THEN_RETRY",
}


# =========================================================
# CUSTOM EXCEPTION
# =========================================================

class RecoveryAlreadyInProgressError(RuntimeError):
    """
    Raised when an idempotent recovery attempt is already
    executing or previously entered an ambiguous error state.
    """

    pass


# =========================================================
# PERSISTENCE CONFIGURATION
# =========================================================

def persistence_enabled() -> bool:
    value = os.getenv(
        "RECOVERAI_PERSISTENCE_ENABLED",
        "false",
    )

    return value.strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def _persistence_warning(operation: str, exc: Exception) -> None:
    """
    Do not print secrets or raw database payloads.

    During the current SIMULATION phase RecoverAI can safely
    fall back to memory if Supabase is unavailable.
    """
    print(
        "[RecoverAI] Supabase persistence unavailable during "
        f"{operation}. Using simulation fallback. "
        f"Error type: {type(exc).__name__}"
    )


# =========================================================
# AUDIT HELPERS
# =========================================================

def create_audit_event(
    step: str,
    status: str,
    message: str,
) -> AuditEvent:
    return AuditEvent(
        step=step,
        status=status,
        message=message,
        timestamp=datetime.now(timezone.utc),
    )


def append_audit_events(
    transaction_id: str,
    events: list[AuditEvent],
) -> None:
    """
    Store a local copy.

    This remains useful for tests and as a temporary
    simulation fallback.
    """
    with STORE_LOCK:
        AUDIT_STORE.setdefault(
            transaction_id,
            [],
        ).extend(events)


def persist_audit_events(
    *,
    transaction_id: str,
    recovery_job_id: str,
    events: list[AuditEvent],
) -> None:
    """
    Persist the exact real execution timestamps generated by
    the recovery flow.
    """
    for event in events:
        persist_audit_event(
            transaction_id=transaction_id,
            recovery_job_id=recovery_job_id,
            step=event.step,
            status=event.status,
            message=event.message,
            created_at=event.timestamp.isoformat(),
        )


# =========================================================
# IN-MEMORY IDEMPOTENCY
# =========================================================

def generate_idempotency_key(
    request: ClassificationRequest,
) -> str:
    """
    Deterministic key:

        transaction_id
        +
        failure_code
        +
        attempt_number

    retry_count represents attempts already made.
    """

    attempt_number = request.retry_count + 1

    token = (
        f"{request.transaction_id}:"
        f"{request.failure_code.value}:"
        f"{attempt_number}"
    )

    return hashlib.sha256(
        token.encode()
    ).hexdigest()


def resolve_idempotency_key(
    request: ClassificationRequest,
) -> str:
    provided_key = getattr(
        request,
        "idempotency_key",
        None,
    )

    if provided_key:
        return str(provided_key)

    return generate_idempotency_key(request)


def reserve_idempotency_key(
    idempotency_key: str,
) -> RecoveryExecutionResponse | None:
    """
    Atomic process-local reservation.
    """

    with STORE_LOCK:

        existing_result = IDEMPOTENCY_RESULT_STORE.get(
            idempotency_key
        )

        if existing_result is not None:
            return existing_result

        existing_state = IDEMPOTENCY_STATE.get(
            idempotency_key
        )

        if existing_state == "IN_PROGRESS":
            raise RecoveryAlreadyInProgressError(
                "A recovery attempt with this idempotency "
                "key is already in progress."
            )

        if existing_state == "ERROR":
            raise RecoveryAlreadyInProgressError(
                "This recovery attempt previously entered "
                "an ambiguous error state. Automatic "
                "re-execution is blocked."
            )

        IDEMPOTENCY_STATE[
            idempotency_key
        ] = "IN_PROGRESS"

    return None


def finalize_idempotency(
    idempotency_key: str,
    response: RecoveryExecutionResponse,
) -> None:
    with STORE_LOCK:

        IDEMPOTENCY_RESULT_STORE[
            idempotency_key
        ] = response

        IDEMPOTENCY_STATE[
            idempotency_key
        ] = "COMPLETED"


def mark_idempotency_error(
    idempotency_key: str,
) -> None:
    with STORE_LOCK:
        IDEMPOTENCY_STATE[
            idempotency_key
        ] = "ERROR"


# =========================================================
# PERSISTENT IDEMPOTENCY
# =========================================================

def response_from_persistent_payload(
    payload: dict,
) -> RecoveryExecutionResponse:
    return RecoveryExecutionResponse.model_validate(
        payload
    )


def check_persistent_idempotency(
    idempotency_key: str,
) -> RecoveryExecutionResponse | None:
    """
    Check PostgreSQL before starting a new recovery.

    If Supabase is temporarily unavailable during the
    current simulation phase, execution can continue through
    the process-local safety path.
    """

    if not persistence_enabled():
        return None

    try:
        job = get_recovery_job_by_idempotency_key(
            idempotency_key
        )
    except Exception as exc:
        _persistence_warning(
            "idempotency lookup",
            exc,
        )
        return None

    if job is None:
        return None

    state = job.get("idempotency_state")

    if state == "COMPLETED":

        payload = job.get("response_payload")

        if not payload:
            raise RecoveryAlreadyInProgressError(
                "Persistent recovery is marked COMPLETED "
                "but has no stored response payload."
            )

        response = response_from_persistent_payload(
            payload
        )

        # Warm local cache.
        finalize_idempotency(
            idempotency_key,
            response,
        )

        return response

    if state == "IN_PROGRESS":
        raise RecoveryAlreadyInProgressError(
            "A persistent recovery attempt with this "
            "idempotency key is already in progress."
        )

    if state == "ERROR":
        raise RecoveryAlreadyInProgressError(
            "This persistent recovery attempt previously "
            "entered an ambiguous error state. Automatic "
            "re-execution is blocked."
        )

    raise RecoveryAlreadyInProgressError(
        "Persistent recovery has an unknown idempotency state."
    )


def reserve_persistent_recovery(
    *,
    request: ClassificationRequest,
    idempotency_key: str,
    action: str,
    guardrail_status: str,
) -> tuple[str | None, RecoveryExecutionResponse | None]:
    """
    Persist the transaction and reserve the recovery job
    before EXECUTE.

    Returns:

        (job_id, None)
            New persistent reservation created.

        (None, existing_response)
            Another process already completed this exact
            idempotent attempt.

        (None, None)
            Persistence disabled/unavailable; simulation
            continues using in-memory fallback.
    """

    if not persistence_enabled():
        return None, None

    try:
        save_transaction(
            request=request,
            payment_status="FAILED",
        )

        job, created = reserve_recovery_job(
            transaction_id=request.transaction_id,
            idempotency_key=idempotency_key,
            action=action,
            guardrail_status=guardrail_status,
            attempt_number=request.retry_count + 1,
            execution_mode="SIMULATION",
        )

    except Exception as exc:
        _persistence_warning(
            "recovery reservation",
            exc,
        )
        return None, None

    if created:
        return str(job["id"]), None

    state = job.get("idempotency_state")

    if state == "COMPLETED":

        payload = job.get("response_payload")

        if not payload:
            raise RecoveryAlreadyInProgressError(
                "Existing persistent recovery completed "
                "without a stored response payload."
            )

        response = response_from_persistent_payload(
            payload
        )

        finalize_idempotency(
            idempotency_key,
            response,
        )

        return None, response

    if state == "IN_PROGRESS":
        raise RecoveryAlreadyInProgressError(
            "Another process already reserved this "
            "recovery attempt."
        )

    if state == "ERROR":
        raise RecoveryAlreadyInProgressError(
            "This persistent recovery attempt is in an "
            "ambiguous ERROR state. Re-execution is blocked."
        )

    raise RecoveryAlreadyInProgressError(
        "Existing persistent recovery has an unknown state."
    )


# =========================================================
# DETERMINISTIC SIMULATION
# =========================================================

def simulate_retry_success(
    transaction_id: str,
    failure_code: FailureCode,
) -> tuple[bool, float]:
    """
    Same transaction ID + failure code always produces
    the same simulation result.
    """

    probability = RETRY_SUCCESS_PROBABILITY.get(
        failure_code,
        0.50,
    )

    token = (
        f"{transaction_id}:"
        f"{failure_code.value}"
    )

    digest = hashlib.sha256(
        token.encode()
    ).hexdigest()

    score = (
        int(digest[:8], 16) % 100
    ) / 100

    success = score < probability

    return success, probability


# =========================================================
# RESPONSE FINALIZATION
# =========================================================

def finalize_response(
    *,
    transaction_id: str,
    idempotency_key: str,
    response: RecoveryExecutionResponse,
    events: list[AuditEvent],
    recovery_job_id: str | None,
) -> RecoveryExecutionResponse:
    """
    Finalize PostgreSQL state first when a persistent
    reservation exists, then maintain the local P0 cache.

    During simulation, persistence errors do not destroy the
    existing demo flow. The database job is marked ERROR
    whenever possible.
    """

    if recovery_job_id is not None:

        try:
            persist_audit_events(
                transaction_id=transaction_id,
                recovery_job_id=recovery_job_id,
                events=events,
            )

            complete_recovery_job(
                job_id=recovery_job_id,
                response_payload=response.model_dump(
                    mode="json"
                ),
                execution_status=(
                    response.execution_status.value
                ),
                recovered_amount=(
                    response.recovered_amount
                ),
                execution_mode=(
                    response.execution_mode
                ),
            )

        except Exception as exc:

            try:
                fail_recovery_job(
                    job_id=recovery_job_id,
                    error_message=(
                        "Persistence finalization failed: "
                        f"{type(exc).__name__}"
                    ),
                )
            except Exception:
                pass

            _persistence_warning(
                "recovery finalization",
                exc,
            )

    append_audit_events(
        transaction_id,
        events,
    )

    finalize_idempotency(
        idempotency_key,
        response,
    )

    return response


# =========================================================
# MAIN RECOVERY EXECUTOR
# =========================================================

def execute_recovery(
    request: ClassificationRequest,
) -> RecoveryExecutionResponse:
    """
    Execute one RecoverAI recovery attempt.

    Flow:

        PERSISTENT IDEMPOTENCY LOOKUP
            ↓
        LOCAL IDEMPOTENCY RESERVATION
            ↓
        DETECT
            ↓
        CLASSIFY
            ↓
        DECIDE
            ↓
        GUARDRAIL
            ↓
        PERSIST TRANSACTION
            ↓
        RESERVE PERSISTENT IDEMPOTENCY
            ↓
        EXECUTE
            ↓
        VERIFY
            ↓
        AUDIT + FINALIZE

    Guardrails are evaluated exactly once.
    """

    idempotency_key = resolve_idempotency_key(
        request
    )

    # -----------------------------------------------------
    # Persistent duplicate check
    # -----------------------------------------------------

    persistent_result = (
        check_persistent_idempotency(
            idempotency_key
        )
    )

    if persistent_result is not None:
        return persistent_result

    # -----------------------------------------------------
    # Process-local duplicate protection
    # -----------------------------------------------------

    existing_result = reserve_idempotency_key(
        idempotency_key
    )

    if existing_result is not None:
        return existing_result

    events: list[AuditEvent] = []

    recovery_job_id: str | None = None

    try:

        # =================================================
        # STEP 1 — DETECT
        # =================================================

        events.append(
            create_audit_event(
                step="DETECT",
                status="SUCCESS",
                message=(
                    "Payment failure detected: "
                    f"{request.failure_code.value}"
                ),
            )
        )

        # =================================================
        # STEP 2 — CLASSIFY
        # =================================================

        classification = classify_failure(
            request
        )

        events.append(
            create_audit_event(
                step="CLASSIFY",
                status="SUCCESS",
                message=(
                    "Failure classified as "
                    f"{classification.category} "
                    "with "
                    f"{classification.confidence:.0%} "
                    "confidence."
                ),
            )
        )

        # =================================================
        # STEP 3 — DECIDE
        # =================================================

        recovery = create_recovery_decision(
            request
        )

        events.append(
            create_audit_event(
                step="DECIDE",
                status="SUCCESS",
                message=(
                    "Recovery action selected: "
                    f"{recovery.action}"
                ),
            )
        )

        # =================================================
        # STEP 4 — GUARDRAIL
        # =================================================
        #
        # Exactly one guardrail evaluation.
        # =================================================

        guardrail = evaluate_guardrails(
            request=request,
            recovery=recovery,
        )

        events.append(
            create_audit_event(
                step="GUARDRAIL",
                status=guardrail.status.value,
                message=guardrail.reason,
            )
        )

        # =================================================
        # PERSIST + RESERVE
        # =================================================
        #
        # Reservation occurs after the deterministic safety
        # decision and before any EXECUTE operation.
        # =================================================

        (
            recovery_job_id,
            raced_existing_response,
        ) = reserve_persistent_recovery(
            request=request,
            idempotency_key=idempotency_key,
            action=recovery.action,
            guardrail_status=(
                guardrail.status.value
            ),
        )

        if raced_existing_response is not None:
            return raced_existing_response

        # =================================================
        # BLOCKED / REVIEW REQUIRED
        # =================================================

        if not guardrail.can_execute:

            if (
                guardrail.status
                == GuardrailStatus.REVIEW_REQUIRED
            ):
                execution_status = (
                    ExecutionStatus.REVIEW_REQUIRED
                )
            else:
                execution_status = (
                    ExecutionStatus.BLOCKED
                )

            response = RecoveryExecutionResponse(
                transaction_id=request.transaction_id,
                amount=request.amount,
                failure_code=request.failure_code,
                category=classification.category,
                action=recovery.action,
                confidence=recovery.confidence,
                guardrail_status=guardrail.status,
                can_execute=False,
                execution_status=execution_status,
                recovered_amount=0,
                simulation_probability=None,
                execution_mode="SIMULATION",
                audit_trail=events,
            )

            # No EXECUTE.
            # No VERIFY.
            # Workflow stops at GUARDRAIL.

            return finalize_response(
                transaction_id=request.transaction_id,
                idempotency_key=idempotency_key,
                response=response,
                events=events,
                recovery_job_id=recovery_job_id,
            )

        # =================================================
        # STEP 5 — EXECUTE RETRY
        # =================================================

        if recovery.action in RETRY_ACTIONS:

            events.append(
                create_audit_event(
                    step="EXECUTE",
                    status="RUNNING",
                    message=(
                        "Executing simulated "
                        f"{recovery.action.lower().replace('_', ' ')}."
                    ),
                )
            )

            success, probability = (
                simulate_retry_success(
                    transaction_id=(
                        request.transaction_id
                    ),
                    failure_code=(
                        request.failure_code
                    ),
                )
            )

            # =============================================
            # STEP 6 — VERIFY
            # =============================================

            if success:

                recovered_amount = request.amount

                execution_status = (
                    ExecutionStatus.RECOVERED
                )

                events.append(
                    create_audit_event(
                        step="VERIFY",
                        status="SUCCESS",
                        message=(
                            "Payment recovery verified. "
                            f"₹{request.amount:,.2f} "
                            "recovered."
                        ),
                    )
                )

            else:

                recovered_amount = 0

                execution_status = (
                    ExecutionStatus.FAILED
                )

                events.append(
                    create_audit_event(
                        step="VERIFY",
                        status="FAILED",
                        message=(
                            "The simulated retry did not "
                            "recover the payment."
                        ),
                    )
                )

        # =================================================
        # CUSTOMER ACTION WORKFLOW
        # =================================================

        elif (
            recovery.status
            == RecoveryStatus.CUSTOMER_ACTION_REQUIRED
        ):

            probability = None
            recovered_amount = 0

            execution_status = (
                ExecutionStatus.ACTION_COMPLETED
            )

            events.append(
                create_audit_event(
                    step="EXECUTE",
                    status="SUCCESS",
                    message=(
                        "Customer recovery action initiated: "
                        f"{recovery.action}"
                    ),
                )
            )

            events.append(
                create_audit_event(
                    step="VERIFY",
                    status="PENDING",
                    message=(
                        "Waiting for customer action "
                        "before revenue can be recovered."
                    ),
                )
            )

        # =================================================
        # SAFE FALLBACK
        # =================================================

        else:

            probability = None
            recovered_amount = 0

            execution_status = (
                ExecutionStatus.FAILED
            )

            events.append(
                create_audit_event(
                    step="EXECUTE",
                    status="FAILED",
                    message=(
                        "No executable recovery action "
                        "was available."
                    ),
                )
            )

            events.append(
                create_audit_event(
                    step="VERIFY",
                    status="FAILED",
                    message=(
                        "Recovery could not be verified "
                        "because no valid execution "
                        "action was completed."
                    ),
                )
            )

        # =================================================
        # FINAL RESPONSE
        # =================================================

        response = RecoveryExecutionResponse(
            transaction_id=request.transaction_id,
            amount=request.amount,
            failure_code=request.failure_code,
            category=classification.category,
            action=recovery.action,
            confidence=recovery.confidence,
            guardrail_status=guardrail.status,
            can_execute=guardrail.can_execute,
            execution_status=execution_status,
            recovered_amount=recovered_amount,
            simulation_probability=probability,
            execution_mode="SIMULATION",
            audit_trail=events,
        )

        return finalize_response(
            transaction_id=request.transaction_id,
            idempotency_key=idempotency_key,
            response=response,
            events=events,
            recovery_job_id=recovery_job_id,
        )

    except Exception as exc:

        # =================================================
        # ERROR HANDLING
        # =================================================

        error_event = create_audit_event(
            step="ERROR",
            status="FAILED",
            message=(
                "Recovery execution encountered "
                "an internal error: "
                f"{type(exc).__name__}"
            ),
        )

        events.append(
            error_event
        )

        append_audit_events(
            transaction_id=request.transaction_id,
            events=events,
        )

        mark_idempotency_error(
            idempotency_key
        )

        if recovery_job_id is not None:

            try:
                persist_audit_events(
                    transaction_id=(
                        request.transaction_id
                    ),
                    recovery_job_id=(
                        recovery_job_id
                    ),
                    events=events,
                )
            except Exception:
                pass

            try:
                fail_recovery_job(
                    job_id=recovery_job_id,
                    error_message=(
                        "Recovery execution failed: "
                        f"{type(exc).__name__}"
                    ),
                )
            except Exception:
                pass

        raise


# =========================================================
# AUDIT READ
# =========================================================

def get_audit_trail(
    transaction_id: str,
) -> list[AuditEvent]:
    """
    Supabase is the preferred runtime audit source.

    If persistence is disabled or unavailable, RecoverAI
    falls back to the local P0 audit store.
    """

    if persistence_enabled():

        try:
            rows = get_audit_events(
                transaction_id
            )

            if rows:
                return [
                    AuditEvent(
                        step=row["step"],
                        status=row["status"],
                        message=row["message"],
                        timestamp=row["created_at"],
                    )
                    for row in rows
                ]

        except Exception as exc:
            _persistence_warning(
                "audit read",
                exc,
            )

    with STORE_LOCK:

        events = AUDIT_STORE.get(
            transaction_id,
            [],
        )

        return list(events)


# =========================================================
# IDEMPOTENCY READ
# =========================================================

def get_idempotency_result(
    idempotency_key: str,
) -> RecoveryExecutionResponse | None:
    """
    Process-local debug/test accessor.
    """

    with STORE_LOCK:
        return IDEMPOTENCY_RESULT_STORE.get(
            idempotency_key
        )


def get_idempotency_state(
    idempotency_key: str,
) -> str | None:
    """
    Process-local debug/test accessor.
    """

    with STORE_LOCK:
        return IDEMPOTENCY_STATE.get(
            idempotency_key
        )